sudo: required
services:
  - docker

before_install:
  - docker build -t saidhstu/docker-react -f Dockerfile.dev .

script:
  - docker run saidhstu/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-west-1-501886758365"
  bucket_path: "frontend"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY